version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: revpay_pro_db
      MYSQL_ROOT_PASSWORD: "@Lakshman.2002"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/revpay_pro_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "@Lakshman.2002"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: